apiVersion: v1
kind: ConfigMap
metadata:
  name: change-port-config
data:
  000-default.conf: |
    <VirtualHost *:8080>
      DocumentRoot /var/www/html
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
  ports.conf: |
    Listen 8080
