apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: change-port-config
      containers:
      - name: php-redis
        volumeMounts:
        - name: config-volume
          mountPath: /etc/apache2/sites-available/000-default.conf
          subPath: 000-default.conf
        - name: config-volume
          mountPath: /etc/apache2/ports.conf
          subPath: ports.conf
        image: registry.fedins.com/e411bcsl/gb-frontend:v5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_LEADER_SERVICE_HOST
          value: redis-leader.guestbook.svc.clusterset.local
        - name: REDIS_FOLLOWER_SERVICE_HOST
          value: redis-follower.guestbook.svc.clusterset.local
        ports:
        - containerPort: 80
